### ISSUE TITLE
Status van student

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/StudentFollowingSystem#14]
De 'status' van een student moet op een bepaalde manier vastgelegd worden. Dit is nodig om bij te houden of de student er goed voor staat of dat deze extra aandacht nodig heeft, bijvoorbeeld in de vorm van een extra gesprek.

Een manier om dit te doen is een groen/oranje/rood systeem hanteren:
- _groen_ geeft aan dat een student er goed voor staat en geen extra aandacht nodig heeft.
- _oranje_ geeft aan dat een student n.a.v. vorig gesprek of behaalde resultaten wellicht op (korte) termijn een gesprek nodig heeft.
- _rood_ geeft aan dat een student n.a.v. vorig gesprek of behaalde resultaten dringend aandacht nodig heeft en er moet op korte termijn een afspraak worden gemaakt.

Todo:
- [ ] Status van een student aanpassen n.a.v. een gesprek
- [ ] Status van een student aanpassen als er cijfers worden ingevoerd
- [ ] Als een gesprek te lang geleden is

**Comment by henkmollema** [comment]
Besproken dat we het rood/oranje/groen systeem gaan gebruiken.

**Comment by henkmollema** [comment]
Hoe gaan we de status aanpassen o.b.v. de cijfers? Zie: #18

**Comment by Lg0enga** [comment]
@henkmollema mijn stoplicht is er jammer genoeg nooit gekomen...

**Comment by henkmollema** [comment]
Staat in de backlog @Lg0enga, je mag 'm oppakken!

**Comment by Lg0enga** [comment]
Ga gelijk aan de gang @henkmollema! :ok_hand:

**Comment by Lg0enga** [comment]
@henkmollema waar is dat stoplicht toch gebleven?...

**Comment by henkmollema** [comment]
Goeie vraag @Lg0enga...
