### ISSUE TITLE
Mail naar student als account is aangemaakt

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/StudentFollowingSystem#28]
De mail naar de studenten toe is nu erg simpel. Wat moet hier in komen te staan?

**Comment by Lg0enga** [comment]
Beste Len ,

Hogeschool NHL maakt gebruikt van het Student volg systeem.
Hier kunnen studenten en SLB'ers de studie voortgang bekijken en bij houden.
De NHL heeft alvast een acount voor je aangenaakt, Dit zijn de gegevens:

Inlognaam: len@goenga.com
Wachtwoord: fifewqti

Met Vriendelijke groet,

 NHL Hogeschool

**Comment by Lg0enga** [comment]
Mail gemaakt met info en gegevens met afzender NHL hogeschool

**Comment by henkmollema** [comment]
Al ge-commit?
